/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityEventAction
 */
export interface CommunityEventAction {
    /**
     * 
     * @type {string}
     * @memberof CommunityEventAction
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CommunityEventAction
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CommunityEventAction
     */
    description: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommunityEventAction
     */
    points: number;
}

/**
 * Check if a given object implements the CommunityEventAction interface.
 */
export function instanceOfCommunityEventAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "points" in value;

    return isInstance;
}

export function CommunityEventActionFromJSON(json: any): CommunityEventAction {
    return CommunityEventActionFromJSONTyped(json, false);
}

export function CommunityEventActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityEventAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'title': json['title'],
        'description': json['description'],
        'points': json['points'],
    };
}

export function CommunityEventActionToJSON(value?: CommunityEventAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'title': value.title,
        'description': value.description,
        'points': value.points,
    };
}

