/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The last message sent
 * @export
 * @interface ConversationForPublicLastMessage
 */
export interface ConversationForPublicLastMessage {
    /**
     * 
     * @type {string}
     * @memberof ConversationForPublicLastMessage
     */
    id: string;
    /**
     * The message content
     * @type {string}
     * @memberof ConversationForPublicLastMessage
     */
    message: string;
}

/**
 * Check if a given object implements the ConversationForPublicLastMessage interface.
 */
export function instanceOfConversationForPublicLastMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ConversationForPublicLastMessageFromJSON(json: any): ConversationForPublicLastMessage {
    return ConversationForPublicLastMessageFromJSONTyped(json, false);
}

export function ConversationForPublicLastMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationForPublicLastMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'message': json['message'],
    };
}

export function ConversationForPublicLastMessageToJSON(value?: ConversationForPublicLastMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': value.id,
        'message': value.message,
    };
}

