/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLockFromSharedLockDto
 */
export interface CreateLockFromSharedLockDto {
    /**
     * The shared lock password, if needed
     * @type {string}
     * @memberof CreateLockFromSharedLockDto
     */
    password?: string;
    /**
     * The combination id
     * @type {string}
     * @memberof CreateLockFromSharedLockDto
     */
    combinationId: string;
    /**
     * Whether the lock is a test lock and counts in the user stats
Only available if the shared lock allows test locks
     * @type {boolean}
     * @memberof CreateLockFromSharedLockDto
     */
    isTestLock: boolean;
}

/**
 * Check if a given object implements the CreateLockFromSharedLockDto interface.
 */
export function instanceOfCreateLockFromSharedLockDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "combinationId" in value;
    isInstance = isInstance && "isTestLock" in value;

    return isInstance;
}

export function CreateLockFromSharedLockDtoFromJSON(json: any): CreateLockFromSharedLockDto {
    return CreateLockFromSharedLockDtoFromJSONTyped(json, false);
}

export function CreateLockFromSharedLockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLockFromSharedLockDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'password') ? undefined : json['password'],
        'combinationId': json['combinationId'],
        'isTestLock': json['isTestLock'],
    };
}

export function CreateLockFromSharedLockDtoToJSON(value?: CreateLockFromSharedLockDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'combinationId': value.combinationId,
        'isTestLock': value.isTestLock,
    };
}

