/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCodeDto
 */
export interface CreateCodeDto {
    /**
     * The code combination
     * @type {string}
     * @memberof CreateCodeDto
     */
    code: string;
}

/**
 * Check if a given object implements the CreateCodeDto interface.
 */
export function instanceOfCreateCodeDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function CreateCodeDtoFromJSON(json: any): CreateCodeDto {
    return CreateCodeDtoFromJSONTyped(json, false);
}

export function CreateCodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCodeDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function CreateCodeDtoToJSON(value?: CreateCodeDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}

