/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOfferRequestDto
 */
export interface CreateOfferRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOfferRequestDto
     */
    keyholder: string;
}

/**
 * Check if a given object implements the CreateOfferRequestDto interface.
 */
export function instanceOfCreateOfferRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "keyholder" in value;

    return isInstance;
}

export function CreateOfferRequestDtoFromJSON(json: any): CreateOfferRequestDto {
    return CreateOfferRequestDtoFromJSONTyped(json, false);
}

export function CreateOfferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOfferRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keyholder': json['keyholder'],
    };
}

export function CreateOfferRequestDtoToJSON(value?: CreateOfferRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keyholder': value.keyholder,
    };
}

