/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageReportItemDto
 */
export interface CreateMessageReportItemDto {
    /**
     * The report type
Equals to `message`
     * @type {string}
     * @memberof CreateMessageReportItemDto
     */
    type: CreateMessageReportItemDtoTypeEnum;
    /**
     * The message id
     * @type {string}
     * @memberof CreateMessageReportItemDto
     */
    messageId: string;
}


/**
 * @export
 */
export const CreateMessageReportItemDtoTypeEnum = {
    Message: 'message'
} as const;
export type CreateMessageReportItemDtoTypeEnum = typeof CreateMessageReportItemDtoTypeEnum[keyof typeof CreateMessageReportItemDtoTypeEnum];


/**
 * Check if a given object implements the CreateMessageReportItemDto interface.
 */
export function instanceOfCreateMessageReportItemDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "messageId" in value;

    return isInstance;
}

export function CreateMessageReportItemDtoFromJSON(json: any): CreateMessageReportItemDto {
    return CreateMessageReportItemDtoFromJSONTyped(json, false);
}

export function CreateMessageReportItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageReportItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'messageId': json['messageId'],
    };
}

export function CreateMessageReportItemDtoToJSON(value?: CreateMessageReportItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'messageId': value.messageId,
    };
}

