/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CreateMessageReportItemDto,
    instanceOfCreateMessageReportItemDto,
    CreateMessageReportItemDtoFromJSON,
    CreateMessageReportItemDtoFromJSONTyped,
    CreateMessageReportItemDtoToJSON,
} from './CreateMessageReportItemDto';
import {
    CreatePostReportItemDto,
    instanceOfCreatePostReportItemDto,
    CreatePostReportItemDtoFromJSON,
    CreatePostReportItemDtoFromJSONTyped,
    CreatePostReportItemDtoToJSON,
} from './CreatePostReportItemDto';

/**
 * @type CreateReportDtoTarget
 * The content to report
 * @export
 */
export type CreateReportDtoTarget = CreateMessageReportItemDto | CreatePostReportItemDto;

export function CreateReportDtoTargetFromJSON(json: any): CreateReportDtoTarget {
    return CreateReportDtoTargetFromJSONTyped(json, false);
}

export function CreateReportDtoTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReportDtoTarget {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...CreateMessageReportItemDtoFromJSONTyped(json, true), ...CreatePostReportItemDtoFromJSONTyped(json, true) };
}

export function CreateReportDtoTargetToJSON(value?: CreateReportDtoTarget | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfCreateMessageReportItemDto(value)) {
        return CreateMessageReportItemDtoToJSON(value as CreateMessageReportItemDto);
    }
    if (instanceOfCreatePostReportItemDto(value)) {
        return CreatePostReportItemDtoToJSON(value as CreatePostReportItemDto);
    }

    return {};
}

