/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConversationDto
 */
export interface CreateConversationDto {
    /**
     * List of user ids in the conversation, excluding the logged user
     * @type {Array<string>}
     * @memberof CreateConversationDto
     */
    users: Array<string>;
    /**
     * The conversation type

The `group` type is currently not supported.
     * @type {string}
     * @memberof CreateConversationDto
     */
    type: CreateConversationDtoTypeEnum;
    /**
     * The file token

Create a file token by using the `/files/upload` endpoint.
     * @type {string}
     * @memberof CreateConversationDto
     */
    attachments?: string;
    /**
     * The message
     * @type {string}
     * @memberof CreateConversationDto
     */
    message: string;
    /**
     * Nonce

If this field is included, it will be returned to the websocket client
     * @type {string}
     * @memberof CreateConversationDto
     */
    nonce?: string;
}


/**
 * @export
 */
export const CreateConversationDtoTypeEnum = {
    Private: 'private',
    Group: 'group'
} as const;
export type CreateConversationDtoTypeEnum = typeof CreateConversationDtoTypeEnum[keyof typeof CreateConversationDtoTypeEnum];


/**
 * Check if a given object implements the CreateConversationDto interface.
 */
export function instanceOfCreateConversationDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "users" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CreateConversationDtoFromJSON(json: any): CreateConversationDto {
    return CreateConversationDtoFromJSONTyped(json, false);
}

export function CreateConversationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConversationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': json['users'],
        'type': json['type'],
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'message': json['message'],
        'nonce': !exists(json, 'nonce') ? undefined : json['nonce'],
    };
}

export function CreateConversationDtoToJSON(value?: CreateConversationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': value.users,
        'type': value.type,
        'attachments': value.attachments,
        'message': value.message,
        'nonce': value.nonce,
    };
}

