/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The user private metadata
 * @export
 * @interface CurrentUserForProfileSettingsPrivateMetadata
 */
export interface CurrentUserForProfileSettingsPrivateMetadata {
    /**
     * 
     * @type {boolean}
     * @memberof CurrentUserForProfileSettingsPrivateMetadata
     */
    locktoberPlusModalPending: boolean;
}

/**
 * Check if a given object implements the CurrentUserForProfileSettingsPrivateMetadata interface.
 */
export function instanceOfCurrentUserForProfileSettingsPrivateMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "locktoberPlusModalPending" in value;

    return isInstance;
}

export function CurrentUserForProfileSettingsPrivateMetadataFromJSON(json: any): CurrentUserForProfileSettingsPrivateMetadata {
    return CurrentUserForProfileSettingsPrivateMetadataFromJSONTyped(json, false);
}

export function CurrentUserForProfileSettingsPrivateMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserForProfileSettingsPrivateMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locktoberPlusModalPending': json['locktoberPlusModalPending'],
    };
}

export function CurrentUserForProfileSettingsPrivateMetadataToJSON(value?: CurrentUserForProfileSettingsPrivateMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locktoberPlusModalPending': value.locktoberPlusModalPending,
    };
}

