/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DurationCriteriaData
 */
export interface DurationCriteriaData {
    /**
     * 
     * @type {number}
     * @memberof DurationCriteriaData
     */
    minDuration: number;
    /**
     * 
     * @type {number}
     * @memberof DurationCriteriaData
     */
    maxDuration: number;
}

/**
 * Check if a given object implements the DurationCriteriaData interface.
 */
export function instanceOfDurationCriteriaData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "minDuration" in value;
    isInstance = isInstance && "maxDuration" in value;

    return isInstance;
}

export function DurationCriteriaDataFromJSON(json: any): DurationCriteriaData {
    return DurationCriteriaDataFromJSONTyped(json, false);
}

export function DurationCriteriaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DurationCriteriaData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minDuration': json['minDuration'],
        'maxDuration': json['maxDuration'],
    };
}

export function DurationCriteriaDataToJSON(value?: DurationCriteriaData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'minDuration': value.minDuration,
        'maxDuration': value.maxDuration,
    };
}

