/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtensionCriteriaData
 */
export interface ExtensionCriteriaData {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtensionCriteriaData
     */
    extensions: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionCriteriaData
     */
    all: boolean;
}

/**
 * Check if a given object implements the ExtensionCriteriaData interface.
 */
export function instanceOfExtensionCriteriaData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "extensions" in value;
    isInstance = isInstance && "all" in value;

    return isInstance;
}

export function ExtensionCriteriaDataFromJSON(json: any): ExtensionCriteriaData {
    return ExtensionCriteriaDataFromJSONTyped(json, false);
}

export function ExtensionCriteriaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtensionCriteriaData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extensions': json['extensions'],
        'all': json['all'],
    };
}

export function ExtensionCriteriaDataToJSON(value?: ExtensionCriteriaData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'extensions': value.extensions,
        'all': value.all,
    };
}

