/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FeatureSwitchEnum = {
    PartnerExtensions: 'partner_extensions',
    CanJoinSharedLockStatus: 'can_join_shared_lock_status',
    Other: 'other',
    Dummy1: 'dummy_1',
    Dummy2: 'dummy_2',
    Dummy3: 'dummy_3'
} as const;
export type FeatureSwitchEnum = typeof FeatureSwitchEnum[keyof typeof FeatureSwitchEnum];


export function FeatureSwitchEnumFromJSON(json: any): FeatureSwitchEnum {
    return FeatureSwitchEnumFromJSONTyped(json, false);
}

export function FeatureSwitchEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureSwitchEnum {
    return json as FeatureSwitchEnum;
}

export function FeatureSwitchEnumToJSON(value?: FeatureSwitchEnum | null): any {
    return value as any;
}

