/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConversationForPublic } from './ConversationForPublic';
import {
    ConversationForPublicFromJSON,
    ConversationForPublicFromJSONTyped,
    ConversationForPublicToJSON,
} from './ConversationForPublic';

/**
 * 
 * @export
 * @interface GetConversationsRepDto
 */
export interface GetConversationsRepDto {
    /**
     * List of conversations
     * @type {Array<ConversationForPublic>}
     * @memberof GetConversationsRepDto
     */
    results: Array<ConversationForPublic>;
    /**
     * The number of results
     * @type {number}
     * @memberof GetConversationsRepDto
     */
    count: number;
    /**
     * Has more
     * @type {boolean}
     * @memberof GetConversationsRepDto
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the GetConversationsRepDto interface.
 */
export function instanceOfGetConversationsRepDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "results" in value;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "hasMore" in value;

    return isInstance;
}

export function GetConversationsRepDtoFromJSON(json: any): GetConversationsRepDto {
    return GetConversationsRepDtoFromJSONTyped(json, false);
}

export function GetConversationsRepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConversationsRepDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ConversationForPublicFromJSON)),
        'count': json['count'],
        'hasMore': json['hasMore'],
    };
}

export function GetConversationsRepDtoToJSON(value?: GetConversationsRepDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': ((value.results as Array<any>).map(ConversationForPublicToJSON)),
        'count': value.count,
        'hasMore': value.hasMore,
    };
}

