/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFavoriteSharedLocksDto
 */
export interface GetFavoriteSharedLocksDto {
    /**
     * 
     * @type {number}
     * @memberof GetFavoriteSharedLocksDto
     */
    limit: number;
    /**
     * 
     * @type {string}
     * @memberof GetFavoriteSharedLocksDto
     */
    lastId?: string;
}

/**
 * Check if a given object implements the GetFavoriteSharedLocksDto interface.
 */
export function instanceOfGetFavoriteSharedLocksDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "limit" in value;

    return isInstance;
}

export function GetFavoriteSharedLocksDtoFromJSON(json: any): GetFavoriteSharedLocksDto {
    return GetFavoriteSharedLocksDtoFromJSONTyped(json, false);
}

export function GetFavoriteSharedLocksDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFavoriteSharedLocksDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
    };
}

export function GetFavoriteSharedLocksDtoToJSON(value?: GetFavoriteSharedLocksDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'limit': value.limit,
        'lastId': value.lastId,
    };
}

