/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFileFromKeyRepDto
 */
export interface GetFileFromKeyRepDto {
    /**
     * The file url
     * @type {string}
     * @memberof GetFileFromKeyRepDto
     */
    url: string;
}

/**
 * Check if a given object implements the GetFileFromKeyRepDto interface.
 */
export function instanceOfGetFileFromKeyRepDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function GetFileFromKeyRepDtoFromJSON(json: any): GetFileFromKeyRepDto {
    return GetFileFromKeyRepDtoFromJSONTyped(json, false);
}

export function GetFileFromKeyRepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFileFromKeyRepDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function GetFileFromKeyRepDtoToJSON(value?: GetFileFromKeyRepDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

