/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLockHistoryDto
 */
export interface GetLockHistoryDto {
    /**
     * If provided, filter by extension slug
     * @type {string}
     * @memberof GetLockHistoryDto
     */
    extension?: string;
    /**
     * Limit
     * @type {number}
     * @memberof GetLockHistoryDto
     */
    limit?: number;
    /**
     * Offset lastId
     * @type {string}
     * @memberof GetLockHistoryDto
     */
    lastId?: string;
}

/**
 * Check if a given object implements the GetLockHistoryDto interface.
 */
export function instanceOfGetLockHistoryDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetLockHistoryDtoFromJSON(json: any): GetLockHistoryDto {
    return GetLockHistoryDtoFromJSONTyped(json, false);
}

export function GetLockHistoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLockHistoryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extension': !exists(json, 'extension') ? undefined : json['extension'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
    };
}

export function GetLockHistoryDtoToJSON(value?: GetLockHistoryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'extension': value.extension,
        'limit': value.limit,
        'lastId': value.lastId,
    };
}

