/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetLockInfoFromExtensionRepDtoLock } from './GetLockInfoFromExtensionRepDtoLock';
import {
    GetLockInfoFromExtensionRepDtoLockFromJSON,
    GetLockInfoFromExtensionRepDtoLockFromJSONTyped,
    GetLockInfoFromExtensionRepDtoLockToJSON,
} from './GetLockInfoFromExtensionRepDtoLock';

/**
 * 
 * @export
 * @interface GetLockInfoFromExtensionRepDto
 */
export interface GetLockInfoFromExtensionRepDto {
    /**
     * The extension configuration. 
     * @type {object}
     * @memberof GetLockInfoFromExtensionRepDto
     */
    extension: object;
    /**
     * 
     * @type {GetLockInfoFromExtensionRepDtoLock}
     * @memberof GetLockInfoFromExtensionRepDto
     */
    lock: GetLockInfoFromExtensionRepDtoLock;
}

/**
 * Check if a given object implements the GetLockInfoFromExtensionRepDto interface.
 */
export function instanceOfGetLockInfoFromExtensionRepDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "extension" in value;
    isInstance = isInstance && "lock" in value;

    return isInstance;
}

export function GetLockInfoFromExtensionRepDtoFromJSON(json: any): GetLockInfoFromExtensionRepDto {
    return GetLockInfoFromExtensionRepDtoFromJSONTyped(json, false);
}

export function GetLockInfoFromExtensionRepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLockInfoFromExtensionRepDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extension': json['extension'],
        'lock': GetLockInfoFromExtensionRepDtoLockFromJSON(json['lock']),
    };
}

export function GetLockInfoFromExtensionRepDtoToJSON(value?: GetLockInfoFromExtensionRepDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'extension': value.extension,
        'lock': GetLockInfoFromExtensionRepDtoLockToJSON(value.lock),
    };
}

