/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPeriodDetailsRepDto
 */
export interface GetPeriodDetailsRepDto {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetPeriodDetailsRepDto
     */
    categories: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GetPeriodDetailsRepDto
     */
    actions: { [key: string]: number; };
    /**
     * 
     * @type {Date}
     * @memberof GetPeriodDetailsRepDto
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetPeriodDetailsRepDto
     */
    end: Date;
}

/**
 * Check if a given object implements the GetPeriodDetailsRepDto interface.
 */
export function instanceOfGetPeriodDetailsRepDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "categories" in value;
    isInstance = isInstance && "actions" in value;
    isInstance = isInstance && "start" in value;
    isInstance = isInstance && "end" in value;

    return isInstance;
}

export function GetPeriodDetailsRepDtoFromJSON(json: any): GetPeriodDetailsRepDto {
    return GetPeriodDetailsRepDtoFromJSONTyped(json, false);
}

export function GetPeriodDetailsRepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPeriodDetailsRepDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categories': json['categories'],
        'actions': json['actions'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
    };
}

export function GetPeriodDetailsRepDtoToJSON(value?: GetPeriodDetailsRepDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categories': value.categories,
        'actions': value.actions,
        'start': (value.start.toISOString()),
        'end': (value.end.toISOString()),
    };
}

