/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPeriodDetailsDto
 */
export interface GetPeriodDetailsDto {
    /**
     * 
     * @type {Date}
     * @memberof GetPeriodDetailsDto
     */
    date: Date;
}

/**
 * Check if a given object implements the GetPeriodDetailsDto interface.
 */
export function instanceOfGetPeriodDetailsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "date" in value;

    return isInstance;
}

export function GetPeriodDetailsDtoFromJSON(json: any): GetPeriodDetailsDto {
    return GetPeriodDetailsDtoFromJSONTyped(json, false);
}

export function GetPeriodDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPeriodDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
    };
}

export function GetPeriodDetailsDtoToJSON(value?: GetPeriodDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': (value.date.toISOString()),
    };
}

