/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsFavoriteSharedLockRepDto
 */
export interface IsFavoriteSharedLockRepDto {
    /**
     * Whether the lock is user favorite
     * @type {boolean}
     * @memberof IsFavoriteSharedLockRepDto
     */
    favorite: boolean;
}

/**
 * Check if a given object implements the IsFavoriteSharedLockRepDto interface.
 */
export function instanceOfIsFavoriteSharedLockRepDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "favorite" in value;

    return isInstance;
}

export function IsFavoriteSharedLockRepDtoFromJSON(json: any): IsFavoriteSharedLockRepDto {
    return IsFavoriteSharedLockRepDtoFromJSONTyped(json, false);
}

export function IsFavoriteSharedLockRepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsFavoriteSharedLockRepDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'favorite': json['favorite'],
    };
}

export function IsFavoriteSharedLockRepDtoToJSON(value?: IsFavoriteSharedLockRepDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'favorite': value.favorite,
    };
}

