/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeycloakGlobalConfig
 */
export interface KeycloakGlobalConfig {
    /**
     * 
     * @type {string}
     * @memberof KeycloakGlobalConfig
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof KeycloakGlobalConfig
     */
    realm: string;
    /**
     * 
     * @type {string}
     * @memberof KeycloakGlobalConfig
     */
    url: string;
}

/**
 * Check if a given object implements the KeycloakGlobalConfig interface.
 */
export function instanceOfKeycloakGlobalConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "realm" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function KeycloakGlobalConfigFromJSON(json: any): KeycloakGlobalConfig {
    return KeycloakGlobalConfigFromJSONTyped(json, false);
}

export function KeycloakGlobalConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeycloakGlobalConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientId': json['clientId'],
        'realm': json['realm'],
        'url': json['url'],
    };
}

export function KeycloakGlobalConfigToJSON(value?: KeycloakGlobalConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientId': value.clientId,
        'realm': value.realm,
        'url': value.url,
    };
}

