/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SharedLocksCriteriaData } from './SharedLocksCriteriaData';
import {
    SharedLocksCriteriaDataFromJSON,
    SharedLocksCriteriaDataFromJSONTyped,
    SharedLocksCriteriaDataToJSON,
} from './SharedLocksCriteriaData';

/**
 * Search criteria
 * @export
 * @interface KeyholderSearchLocksDtoCriteria
 */
export interface KeyholderSearchLocksDtoCriteria {
    /**
     * 
     * @type {SharedLocksCriteriaData}
     * @memberof KeyholderSearchLocksDtoCriteria
     */
    sharedLocks?: SharedLocksCriteriaData;
}

/**
 * Check if a given object implements the KeyholderSearchLocksDtoCriteria interface.
 */
export function instanceOfKeyholderSearchLocksDtoCriteria(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KeyholderSearchLocksDtoCriteriaFromJSON(json: any): KeyholderSearchLocksDtoCriteria {
    return KeyholderSearchLocksDtoCriteriaFromJSONTyped(json, false);
}

export function KeyholderSearchLocksDtoCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyholderSearchLocksDtoCriteria {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sharedLocks': !exists(json, 'sharedLocks') ? undefined : SharedLocksCriteriaDataFromJSON(json['sharedLocks']),
    };
}

export function KeyholderSearchLocksDtoCriteriaToJSON(value?: KeyholderSearchLocksDtoCriteria | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sharedLocks': SharedLocksCriteriaDataToJSON(value.sharedLocks),
    };
}

