/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockControllerSetMaxLimitDate400Response
 */
export interface LockControllerSetMaxLimitDate400Response {
}

/**
 * Check if a given object implements the LockControllerSetMaxLimitDate400Response interface.
 */
export function instanceOfLockControllerSetMaxLimitDate400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LockControllerSetMaxLimitDate400ResponseFromJSON(json: any): LockControllerSetMaxLimitDate400Response {
    return LockControllerSetMaxLimitDate400ResponseFromJSONTyped(json, false);
}

export function LockControllerSetMaxLimitDate400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockControllerSetMaxLimitDate400Response {
    return json;
}

export function LockControllerSetMaxLimitDate400ResponseToJSON(value?: LockControllerSetMaxLimitDate400Response | null): any {
    return value;
}

