/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The last verification picture
 * @export
 * @interface LockForPublicLastVerificationPicture
 */
export interface LockForPublicLastVerificationPicture {
    /**
     * 
     * @type {string}
     * @memberof LockForPublicLastVerificationPicture
     */
    imageFile: string;
    /**
     * 
     * @type {string}
     * @memberof LockForPublicLastVerificationPicture
     */
    imageKey: string;
    /**
     * 
     * @type {Date}
     * @memberof LockForPublicLastVerificationPicture
     */
    submittedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof LockForPublicLastVerificationPicture
     */
    verificationCode: string;
    /**
     * 
     * @type {string}
     * @memberof LockForPublicLastVerificationPicture
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof LockForPublicLastVerificationPicture
     */
    peerVerificationId?: string;
}

/**
 * Check if a given object implements the LockForPublicLastVerificationPicture interface.
 */
export function instanceOfLockForPublicLastVerificationPicture(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "imageFile" in value;
    isInstance = isInstance && "imageKey" in value;
    isInstance = isInstance && "submittedAt" in value;
    isInstance = isInstance && "verificationCode" in value;

    return isInstance;
}

export function LockForPublicLastVerificationPictureFromJSON(json: any): LockForPublicLastVerificationPicture {
    return LockForPublicLastVerificationPictureFromJSONTyped(json, false);
}

export function LockForPublicLastVerificationPictureFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockForPublicLastVerificationPicture {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageFile': json['imageFile'],
        'imageKey': json['imageKey'],
        'submittedAt': (new Date(json['submittedAt'])),
        'verificationCode': json['verificationCode'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'peerVerificationId': !exists(json, 'peerVerificationId') ? undefined : json['peerVerificationId'],
    };
}

export function LockForPublicLastVerificationPictureToJSON(value?: LockForPublicLastVerificationPicture | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'imageFile': value.imageFile,
        'imageKey': value.imageKey,
        'submittedAt': (value.submittedAt.toISOString()),
        'verificationCode': value.verificationCode,
        'filename': value.filename,
        'peerVerificationId': value.peerVerificationId,
    };
}

