/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LockStatusEnum = {
    Locked: 'locked',
    Unlocked: 'unlocked',
    Deserted: 'deserted'
} as const;
export type LockStatusEnum = typeof LockStatusEnum[keyof typeof LockStatusEnum];


export function LockStatusEnumFromJSON(json: any): LockStatusEnum {
    return LockStatusEnumFromJSONTyped(json, false);
}

export function LockStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockStatusEnum {
    return json as LockStatusEnum;
}

export function LockStatusEnumToJSON(value?: LockStatusEnum | null): any {
    return value as any;
}

