/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockControllerTrustKeyholder400Response
 */
export interface LockControllerTrustKeyholder400Response {
}

/**
 * Check if a given object implements the LockControllerTrustKeyholder400Response interface.
 */
export function instanceOfLockControllerTrustKeyholder400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LockControllerTrustKeyholder400ResponseFromJSON(json: any): LockControllerTrustKeyholder400Response {
    return LockControllerTrustKeyholder400ResponseFromJSONTyped(json, false);
}

export function LockControllerTrustKeyholder400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockControllerTrustKeyholder400Response {
    return json;
}

export function LockControllerTrustKeyholder400ResponseToJSON(value?: LockControllerTrustKeyholder400Response | null): any {
    return value;
}

