/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerConfigurationChildCapabilitiesFeatures
 */
export interface PartnerConfigurationChildCapabilitiesFeatures {
    /**
     * 
     * @type {boolean}
     * @memberof PartnerConfigurationChildCapabilitiesFeatures
     */
    save: boolean;
}

/**
 * Check if a given object implements the PartnerConfigurationChildCapabilitiesFeatures interface.
 */
export function instanceOfPartnerConfigurationChildCapabilitiesFeatures(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "save" in value;

    return isInstance;
}

export function PartnerConfigurationChildCapabilitiesFeaturesFromJSON(json: any): PartnerConfigurationChildCapabilitiesFeatures {
    return PartnerConfigurationChildCapabilitiesFeaturesFromJSONTyped(json, false);
}

export function PartnerConfigurationChildCapabilitiesFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerConfigurationChildCapabilitiesFeatures {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'save': json['save'],
    };
}

export function PartnerConfigurationChildCapabilitiesFeaturesToJSON(value?: PartnerConfigurationChildCapabilitiesFeatures | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'save': value.save,
    };
}

