/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PartnerConfigurationChildEventEnum = {
    Capabilities: 'capabilities',
    SaveLoading: 'save_loading',
    SaveSuccess: 'save_success',
    SaveFailed: 'save_failed'
} as const;
export type PartnerConfigurationChildEventEnum = typeof PartnerConfigurationChildEventEnum[keyof typeof PartnerConfigurationChildEventEnum];


export function PartnerConfigurationChildEventEnumFromJSON(json: any): PartnerConfigurationChildEventEnum {
    return PartnerConfigurationChildEventEnumFromJSONTyped(json, false);
}

export function PartnerConfigurationChildEventEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerConfigurationChildEventEnum {
    return json as PartnerConfigurationChildEventEnum;
}

export function PartnerConfigurationChildEventEnumToJSON(value?: PartnerConfigurationChildEventEnum | null): any {
    return value as any;
}

