/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicLockJoinRules
 */
export interface PublicLockJoinRules {
    /**
     * 
     * @type {boolean}
     * @memberof PublicLockJoinRules
     */
    canBeJoined: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PublicLockJoinRules
     */
    containsPremiumExtension: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PublicLockJoinRules
     */
    exceedsExtensionLimit: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PublicLockJoinRules
     */
    oneOfExtensionsDisabled: boolean;
}

/**
 * Check if a given object implements the PublicLockJoinRules interface.
 */
export function instanceOfPublicLockJoinRules(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "canBeJoined" in value;
    isInstance = isInstance && "containsPremiumExtension" in value;
    isInstance = isInstance && "exceedsExtensionLimit" in value;
    isInstance = isInstance && "oneOfExtensionsDisabled" in value;

    return isInstance;
}

export function PublicLockJoinRulesFromJSON(json: any): PublicLockJoinRules {
    return PublicLockJoinRulesFromJSONTyped(json, false);
}

export function PublicLockJoinRulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicLockJoinRules {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'canBeJoined': json['canBeJoined'],
        'containsPremiumExtension': json['containsPremiumExtension'],
        'exceedsExtensionLimit': json['exceedsExtensionLimit'],
        'oneOfExtensionsDisabled': json['oneOfExtensionsDisabled'],
    };
}

export function PublicLockJoinRulesToJSON(value?: PublicLockJoinRules | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'canBeJoined': value.canBeJoined,
        'containsPremiumExtension': value.containsPremiumExtension,
        'exceedsExtensionLimit': value.exceedsExtensionLimit,
        'oneOfExtensionsDisabled': value.oneOfExtensionsDisabled,
    };
}

