/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReasonPreventingUnlocking
 */
export interface ReasonPreventingUnlocking {
    /**
     * 
     * @type {string}
     * @memberof ReasonPreventingUnlocking
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof ReasonPreventingUnlocking
     */
    icon: string;
}

/**
 * Check if a given object implements the ReasonPreventingUnlocking interface.
 */
export function instanceOfReasonPreventingUnlocking(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reason" in value;
    isInstance = isInstance && "icon" in value;

    return isInstance;
}

export function ReasonPreventingUnlockingFromJSON(json: any): ReasonPreventingUnlocking {
    return ReasonPreventingUnlockingFromJSONTyped(json, false);
}

export function ReasonPreventingUnlockingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReasonPreventingUnlocking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'icon': json['icon'],
    };
}

export function ReasonPreventingUnlockingToJSON(value?: ReasonPreventingUnlocking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reason': value.reason,
        'icon': value.icon,
    };
}

