/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchUserUsernameDto
 */
export interface SearchUserUsernameDto {
    /**
     * 
     * @type {string}
     * @memberof SearchUserUsernameDto
     */
    search: string;
}

/**
 * Check if a given object implements the SearchUserUsernameDto interface.
 */
export function instanceOfSearchUserUsernameDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "search" in value;

    return isInstance;
}

export function SearchUserUsernameDtoFromJSON(json: any): SearchUserUsernameDto {
    return SearchUserUsernameDtoFromJSONTyped(json, false);
}

export function SearchUserUsernameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchUserUsernameDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'search': json['search'],
    };
}

export function SearchUserUsernameDtoToJSON(value?: SearchUserUsernameDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'search': value.search,
    };
}

