/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DurationCriteriaData } from './DurationCriteriaData';
import {
    DurationCriteriaDataFromJSON,
    DurationCriteriaDataFromJSONTyped,
    DurationCriteriaDataToJSON,
} from './DurationCriteriaData';
import type { ExtensionCriteriaData } from './ExtensionCriteriaData';
import {
    ExtensionCriteriaDataFromJSON,
    ExtensionCriteriaDataFromJSONTyped,
    ExtensionCriteriaDataToJSON,
} from './ExtensionCriteriaData';

/**
 * 
 * @export
 * @interface SearchPublicLockDtoCriteria
 */
export interface SearchPublicLockDtoCriteria {
    /**
     * 
     * @type {DurationCriteriaData}
     * @memberof SearchPublicLockDtoCriteria
     */
    duration: DurationCriteriaData;
    /**
     * 
     * @type {ExtensionCriteriaData}
     * @memberof SearchPublicLockDtoCriteria
     */
    extensions: ExtensionCriteriaData;
}

/**
 * Check if a given object implements the SearchPublicLockDtoCriteria interface.
 */
export function instanceOfSearchPublicLockDtoCriteria(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "duration" in value;
    isInstance = isInstance && "extensions" in value;

    return isInstance;
}

export function SearchPublicLockDtoCriteriaFromJSON(json: any): SearchPublicLockDtoCriteria {
    return SearchPublicLockDtoCriteriaFromJSONTyped(json, false);
}

export function SearchPublicLockDtoCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPublicLockDtoCriteria {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'duration': DurationCriteriaDataFromJSON(json['duration']),
        'extensions': ExtensionCriteriaDataFromJSON(json['extensions']),
    };
}

export function SearchPublicLockDtoCriteriaToJSON(value?: SearchPublicLockDtoCriteria | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'duration': DurationCriteriaDataToJSON(value.duration),
        'extensions': ExtensionCriteriaDataToJSON(value.extensions),
    };
}

