/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PublicLockForSearch } from './PublicLockForSearch';
import {
    PublicLockForSearchFromJSON,
    PublicLockForSearchFromJSONTyped,
    PublicLockForSearchToJSON,
} from './PublicLockForSearch';

/**
 * 
 * @export
 * @interface SearchPublicLockRepDto
 */
export interface SearchPublicLockRepDto {
    /**
     * 
     * @type {number}
     * @memberof SearchPublicLockRepDto
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof SearchPublicLockRepDto
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<PublicLockForSearch>}
     * @memberof SearchPublicLockRepDto
     */
    results: Array<PublicLockForSearch>;
}

/**
 * Check if a given object implements the SearchPublicLockRepDto interface.
 */
export function instanceOfSearchPublicLockRepDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "hasMore" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function SearchPublicLockRepDtoFromJSON(json: any): SearchPublicLockRepDto {
    return SearchPublicLockRepDtoFromJSONTyped(json, false);
}

export function SearchPublicLockRepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPublicLockRepDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'hasMore': json['hasMore'],
        'results': ((json['results'] as Array<any>).map(PublicLockForSearchFromJSON)),
    };
}

export function SearchPublicLockRepDtoToJSON(value?: SearchPublicLockRepDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'hasMore': value.hasMore,
        'results': ((value.results as Array<any>).map(PublicLockForSearchToJSON)),
    };
}

