/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SearchPublicLockDtoCriteria } from './SearchPublicLockDtoCriteria';
import {
    SearchPublicLockDtoCriteriaFromJSON,
    SearchPublicLockDtoCriteriaFromJSONTyped,
    SearchPublicLockDtoCriteriaToJSON,
} from './SearchPublicLockDtoCriteria';

/**
 * 
 * @export
 * @interface SearchPublicLockDto
 */
export interface SearchPublicLockDto {
    /**
     * 
     * @type {SearchPublicLockDtoCriteria}
     * @memberof SearchPublicLockDto
     */
    criteria: SearchPublicLockDtoCriteria;
    /**
     * 
     * @type {number}
     * @memberof SearchPublicLockDto
     */
    limit: number;
    /**
     * 
     * @type {string}
     * @memberof SearchPublicLockDto
     */
    lastId?: string;
}

/**
 * Check if a given object implements the SearchPublicLockDto interface.
 */
export function instanceOfSearchPublicLockDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "criteria" in value;
    isInstance = isInstance && "limit" in value;

    return isInstance;
}

export function SearchPublicLockDtoFromJSON(json: any): SearchPublicLockDto {
    return SearchPublicLockDtoFromJSONTyped(json, false);
}

export function SearchPublicLockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPublicLockDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'criteria': SearchPublicLockDtoCriteriaFromJSON(json['criteria']),
        'limit': json['limit'],
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
    };
}

export function SearchPublicLockDtoToJSON(value?: SearchPublicLockDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'criteria': SearchPublicLockDtoCriteriaToJSON(value.criteria),
        'limit': value.limit,
        'lastId': value.lastId,
    };
}

