/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserForPublic } from './UserForPublic';
import {
    UserForPublicFromJSON,
    UserForPublicFromJSONTyped,
    UserForPublicToJSON,
} from './UserForPublic';

/**
 * 
 * @export
 * @interface SessionOfferRequestForKeyholder
 */
export interface SessionOfferRequestForKeyholder {
    /**
     * 
     * @type {string}
     * @memberof SessionOfferRequestForKeyholder
     */
    keyholder: string;
    /**
     * 
     * @type {UserForPublic}
     * @memberof SessionOfferRequestForKeyholder
     */
    lock: UserForPublic;
    /**
     * 
     * @type {string}
     * @memberof SessionOfferRequestForKeyholder
     */
    status: SessionOfferRequestForKeyholderStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof SessionOfferRequestForKeyholder
     */
    validatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SessionOfferRequestForKeyholder
     */
    archivedAt?: Date;
}


/**
 * @export
 */
export const SessionOfferRequestForKeyholderStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Rejected: 'rejected'
} as const;
export type SessionOfferRequestForKeyholderStatusEnum = typeof SessionOfferRequestForKeyholderStatusEnum[keyof typeof SessionOfferRequestForKeyholderStatusEnum];


/**
 * Check if a given object implements the SessionOfferRequestForKeyholder interface.
 */
export function instanceOfSessionOfferRequestForKeyholder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "keyholder" in value;
    isInstance = isInstance && "lock" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function SessionOfferRequestForKeyholderFromJSON(json: any): SessionOfferRequestForKeyholder {
    return SessionOfferRequestForKeyholderFromJSONTyped(json, false);
}

export function SessionOfferRequestForKeyholderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionOfferRequestForKeyholder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keyholder': json['keyholder'],
        'lock': UserForPublicFromJSON(json['lock']),
        'status': json['status'],
        'validatedAt': !exists(json, 'validatedAt') ? undefined : (new Date(json['validatedAt'])),
        'archivedAt': !exists(json, 'archivedAt') ? undefined : (new Date(json['archivedAt'])),
    };
}

export function SessionOfferRequestForKeyholderToJSON(value?: SessionOfferRequestForKeyholder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keyholder': value.keyholder,
        'lock': UserForPublicToJSON(value.lock),
        'status': value.status,
        'validatedAt': value.validatedAt === undefined ? undefined : (value.validatedAt.toISOString()),
        'archivedAt': value.archivedAt === undefined ? undefined : (value.archivedAt.toISOString()),
    };
}

