/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetConversationStatusDto
 */
export interface SetConversationStatusDto {
    /**
     * The new conversation status
     * @type {string}
     * @memberof SetConversationStatusDto
     */
    status: SetConversationStatusDtoStatusEnum;
}


/**
 * @export
 */
export const SetConversationStatusDtoStatusEnum = {
    Approved: 'approved',
    Ignored: 'ignored'
} as const;
export type SetConversationStatusDtoStatusEnum = typeof SetConversationStatusDtoStatusEnum[keyof typeof SetConversationStatusDtoStatusEnum];


/**
 * Check if a given object implements the SetConversationStatusDto interface.
 */
export function instanceOfSetConversationStatusDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function SetConversationStatusDtoFromJSON(json: any): SetConversationStatusDto {
    return SetConversationStatusDtoFromJSONTyped(json, false);
}

export function SetConversationStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetConversationStatusDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function SetConversationStatusDtoToJSON(value?: SetConversationStatusDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

