/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetLockSettingsDto
 */
export interface SetLockSettingsDto {
    /**
     * Whether the remaining time is displayed to the wearer
     * @type {boolean}
     * @memberof SetLockSettingsDto
     */
    displayRemainingTime?: boolean;
    /**
     * Whether the time information should be hidden from the history
     * @type {boolean}
     * @memberof SetLockSettingsDto
     */
    hideTimeLogs?: boolean;
}

/**
 * Check if a given object implements the SetLockSettingsDto interface.
 */
export function instanceOfSetLockSettingsDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SetLockSettingsDtoFromJSON(json: any): SetLockSettingsDto {
    return SetLockSettingsDtoFromJSONTyped(json, false);
}

export function SetLockSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetLockSettingsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayRemainingTime': !exists(json, 'displayRemainingTime') ? undefined : json['displayRemainingTime'],
        'hideTimeLogs': !exists(json, 'hideTimeLogs') ? undefined : json['hideTimeLogs'],
    };
}

export function SetLockSettingsDtoToJSON(value?: SetLockSettingsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'displayRemainingTime': value.displayRemainingTime,
        'hideTimeLogs': value.hideTimeLogs,
    };
}

