/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SharedLockDurationModeEnum = {
    Duration: 'duration',
    Date: 'date'
} as const;
export type SharedLockDurationModeEnum = typeof SharedLockDurationModeEnum[keyof typeof SharedLockDurationModeEnum];


export function SharedLockDurationModeEnumFromJSON(json: any): SharedLockDurationModeEnum {
    return SharedLockDurationModeEnumFromJSONTyped(json, false);
}

export function SharedLockDurationModeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedLockDurationModeEnum {
    return json as SharedLockDurationModeEnum;
}

export function SharedLockDurationModeEnumToJSON(value?: SharedLockDurationModeEnum | null): any {
    return value as any;
}

