/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The Unsplash photo
 * @export
 * @interface SharedLockForPublicUnsplashPhoto
 */
export interface SharedLockForPublicUnsplashPhoto {
    /**
     * 
     * @type {string}
     * @memberof SharedLockForPublicUnsplashPhoto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SharedLockForPublicUnsplashPhoto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof SharedLockForPublicUnsplashPhoto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SharedLockForPublicUnsplashPhoto
     */
    url: string;
}

/**
 * Check if a given object implements the SharedLockForPublicUnsplashPhoto interface.
 */
export function instanceOfSharedLockForPublicUnsplashPhoto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function SharedLockForPublicUnsplashPhotoFromJSON(json: any): SharedLockForPublicUnsplashPhoto {
    return SharedLockForPublicUnsplashPhotoFromJSONTyped(json, false);
}

export function SharedLockForPublicUnsplashPhotoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedLockForPublicUnsplashPhoto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'name': json['name'],
        'url': json['url'],
    };
}

export function SharedLockForPublicUnsplashPhotoToJSON(value?: SharedLockForPublicUnsplashPhoto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
        'name': value.name,
        'url': value.url,
    };
}

