/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerExtensionActionDto
 */
export interface TriggerExtensionActionDto {
    /**
     * The action name
Refer to the extension documentation to know the available actions
     * @type {string}
     * @memberof TriggerExtensionActionDto
     */
    action: string;
    /**
     * The action payload
     * @type {object}
     * @memberof TriggerExtensionActionDto
     */
    payload: object;
}

/**
 * Check if a given object implements the TriggerExtensionActionDto interface.
 */
export function instanceOfTriggerExtensionActionDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "payload" in value;

    return isInstance;
}

export function TriggerExtensionActionDtoFromJSON(json: any): TriggerExtensionActionDto {
    return TriggerExtensionActionDtoFromJSONTyped(json, false);
}

export function TriggerExtensionActionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerExtensionActionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'payload': json['payload'],
    };
}

export function TriggerExtensionActionDtoToJSON(value?: TriggerExtensionActionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'payload': value.payload,
    };
}

