/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateConversationDto
 */
export interface UpdateConversationDto {
    /**
     * The file token

Create a file token by using the `/files/upload` endpoint.
     * @type {string}
     * @memberof UpdateConversationDto
     */
    attachments?: string;
    /**
     * The message
     * @type {string}
     * @memberof UpdateConversationDto
     */
    message: string;
    /**
     * Nonce

If this field is included, it will be returned to the websocket client
     * @type {string}
     * @memberof UpdateConversationDto
     */
    nonce?: string;
}

/**
 * Check if a given object implements the UpdateConversationDto interface.
 */
export function instanceOfUpdateConversationDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateConversationDtoFromJSON(json: any): UpdateConversationDto {
    return UpdateConversationDtoFromJSONTyped(json, false);
}

export function UpdateConversationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConversationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'message': json['message'],
        'nonce': !exists(json, 'nonce') ? undefined : json['nonce'],
    };
}

export function UpdateConversationDtoToJSON(value?: UpdateConversationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attachments': value.attachments,
        'message': value.message,
        'nonce': value.nonce,
    };
}

