/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTimeDto
 */
export interface UpdateTimeDto {
    /**
     * The duration to add, in seconds

Wearer can only add duration (positive values),
unlike keyholders who can add or remove time.
     * @type {number}
     * @memberof UpdateTimeDto
     */
    duration: number;
}

/**
 * Check if a given object implements the UpdateTimeDto interface.
 */
export function instanceOfUpdateTimeDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "duration" in value;

    return isInstance;
}

export function UpdateTimeDtoFromJSON(json: any): UpdateTimeDto {
    return UpdateTimeDtoFromJSONTyped(json, false);
}

export function UpdateTimeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTimeDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'duration': json['duration'],
    };
}

export function UpdateTimeDtoToJSON(value?: UpdateTimeDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'duration': value.duration,
    };
}

