/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFilesDto
 */
export interface UploadFilesDto {
    /**
     * The files to upload
     * @type {Array<Array<Blob>>}
     * @memberof UploadFilesDto
     */
    files: Array<Array<Blob>>;
    /**
     * The target storage
     * @type {string}
     * @memberof UploadFilesDto
     */
    type: UploadFilesDtoTypeEnum;
}


/**
 * @export
 */
export const UploadFilesDtoTypeEnum = {
    Messaging: 'messaging'
} as const;
export type UploadFilesDtoTypeEnum = typeof UploadFilesDtoTypeEnum[keyof typeof UploadFilesDtoTypeEnum];


/**
 * Check if a given object implements the UploadFilesDto interface.
 */
export function instanceOfUploadFilesDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "files" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function UploadFilesDtoFromJSON(json: any): UploadFilesDto {
    return UploadFilesDtoFromJSONTyped(json, false);
}

export function UploadFilesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFilesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'files': json['files'],
        'type': json['type'],
    };
}

export function UploadFilesDtoToJSON(value?: UploadFilesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'files': value.files,
        'type': value.type,
    };
}

