/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadCombinationImageDto
 */
export interface UploadCombinationImageDto {
    /**
     * The combination image
     * @type {Array<Blob>}
     * @memberof UploadCombinationImageDto
     */
    file: Array<Blob>;
    /**
     * Enables the manual combination image check, for Premium users.
     * @type {boolean}
     * @memberof UploadCombinationImageDto
     */
    enableManualCheck?: boolean;
}

/**
 * Check if a given object implements the UploadCombinationImageDto interface.
 */
export function instanceOfUploadCombinationImageDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function UploadCombinationImageDtoFromJSON(json: any): UploadCombinationImageDto {
    return UploadCombinationImageDtoFromJSONTyped(json, false);
}

export function UploadCombinationImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadCombinationImageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
        'enableManualCheck': !exists(json, 'enableManualCheck') ? undefined : json['enableManualCheck'],
    };
}

export function UploadCombinationImageDtoToJSON(value?: UploadCombinationImageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
        'enableManualCheck': value.enableManualCheck,
    };
}

