/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFilesRepDto
 */
export interface UploadFilesRepDto {
    /**
     * The attachment token

It can be used in messaging, post and other endpoints that support
attachments
     * @type {string}
     * @memberof UploadFilesRepDto
     */
    token: string;
}

/**
 * Check if a given object implements the UploadFilesRepDto interface.
 */
export function instanceOfUploadFilesRepDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function UploadFilesRepDtoFromJSON(json: any): UploadFilesRepDto {
    return UploadFilesRepDtoFromJSONTyped(json, false);
}

export function UploadFilesRepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFilesRepDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function UploadFilesRepDtoToJSON(value?: UploadFilesRepDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

