/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPrivateMetadata
 */
export interface UserPrivateMetadata {
    /**
     * 
     * @type {boolean}
     * @memberof UserPrivateMetadata
     */
    locktoberPlusModalPending: boolean;
}

/**
 * Check if a given object implements the UserPrivateMetadata interface.
 */
export function instanceOfUserPrivateMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "locktoberPlusModalPending" in value;

    return isInstance;
}

export function UserPrivateMetadataFromJSON(json: any): UserPrivateMetadata {
    return UserPrivateMetadataFromJSONTyped(json, false);
}

export function UserPrivateMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPrivateMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locktoberPlusModalPending': json['locktoberPlusModalPending'],
    };
}

export function UserPrivateMetadataToJSON(value?: UserPrivateMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locktoberPlusModalPending': value.locktoberPlusModalPending,
    };
}

