/* tslint:disable */
/* eslint-disable */
/**
 * Chaster
 * Chaster Public API  API documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction) 
 *
 * The version of the OpenAPI document: 0.12.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VerificationPictureHistoryEntryVotes } from './VerificationPictureHistoryEntryVotes';
import {
    VerificationPictureHistoryEntryVotesFromJSON,
    VerificationPictureHistoryEntryVotesFromJSONTyped,
    VerificationPictureHistoryEntryVotesToJSON,
} from './VerificationPictureHistoryEntryVotes';

/**
 * 
 * @export
 * @interface VerificationPictureHistoryEntry
 */
export interface VerificationPictureHistoryEntry {
    /**
     * The verification code
     * @type {string}
     * @memberof VerificationPictureHistoryEntry
     */
    verificationCode?: string;
    /**
     * The peer verification id
     * @type {string}
     * @memberof VerificationPictureHistoryEntry
     */
    peerVerificationId?: string;
    /**
     * The peer verification image key
     * @type {string}
     * @memberof VerificationPictureHistoryEntry
     */
    imageKey: string;
    /**
     * Submitted at
     * @type {Date}
     * @memberof VerificationPictureHistoryEntry
     */
    submittedAt: Date;
    /**
     * 
     * @type {VerificationPictureHistoryEntryVotes}
     * @memberof VerificationPictureHistoryEntry
     */
    votes?: VerificationPictureHistoryEntryVotes;
}

/**
 * Check if a given object implements the VerificationPictureHistoryEntry interface.
 */
export function instanceOfVerificationPictureHistoryEntry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "imageKey" in value;
    isInstance = isInstance && "submittedAt" in value;

    return isInstance;
}

export function VerificationPictureHistoryEntryFromJSON(json: any): VerificationPictureHistoryEntry {
    return VerificationPictureHistoryEntryFromJSONTyped(json, false);
}

export function VerificationPictureHistoryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationPictureHistoryEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'verificationCode': !exists(json, 'verificationCode') ? undefined : json['verificationCode'],
        'peerVerificationId': !exists(json, 'peerVerificationId') ? undefined : json['peerVerificationId'],
        'imageKey': json['imageKey'],
        'submittedAt': (new Date(json['submittedAt'])),
        'votes': !exists(json, 'votes') ? undefined : VerificationPictureHistoryEntryVotesFromJSON(json['votes']),
    };
}

export function VerificationPictureHistoryEntryToJSON(value?: VerificationPictureHistoryEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'verificationCode': value.verificationCode,
        'peerVerificationId': value.peerVerificationId,
        'imageKey': value.imageKey,
        'submittedAt': (value.submittedAt.toISOString()),
        'votes': VerificationPictureHistoryEntryVotesToJSON(value.votes),
    };
}

